namespace Logic.Domain.CodeAnalysis.Contract.DataClasses.Level5;

public enum SyntaxTokenKind
{
    Dot,
    Comma,
    Colon,
    Semicolon,
    Underscore,
    Not,
    EqualsSign,
    Complement,
    Minus,
    Plus,
    Mul,
    Div,
    Mod,
    And,
    AndAnd,
    Or,
    OrOr,
    Xor,

    Equals,
    NotEquals,
    SmallerEquals,
    GreaterEquals,
    PlusEquals,
    MinusEquals,
    MulEquals,
    DivEquals,
    ModEquals,
    AndEquals,
    OrEquals,
    XorEquals,
    LeftShiftEquals,
    RightShiftEquals,
    ArrowRight,
    Decrement,
    Increment,
    Smaller,
    Greater,
    LeftShift,
    RightShift,
    Infinite,

    ParenOpen,
    ParenClose,
    CurlyOpen,
    CurlyClose,
    BracketOpen,
    BracketClose,

    Trivia,

    StringLiteral,
    NumericLiteral,
    UnsignedNumericLiteral,
    HashNumericLiteral,
    HashStringLiteral,
    FloatingNumericLiteral,

    Identifier,
    Variable,

    NewKeyword,
    YieldKeyword,
    ReturnKeyword,
    ExitKeyword,
    NotKeyword,
    OrKeyword,
    AndKeyword,
    SwitchKeyword,
    GotoKeyword,
    IfKeyword,
    ElseKeyword,
    WhileKeyword,
    ForKeyword,
    DoKeyword,
    BreakKeyword,
    ContinueKeyword,
    GlobalKeyword,
    TrueKeyword,
    IntKeyword,
    BoolKeyword,
    FloatKeyword,
    NanKeyword,
    InfinityKeyword,
    InfKeyword,
    UndefinedKeyword,

    EndOfFile
}